### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [vitaliigrybov/f1-3-c2p1-colmar-academy#5]
Grade: Exceeds expectations

Summary: Great job on this project, the site looks exceptional on both mobile and desktop. Your transitions are working great and you used a lot of good techniques. Take a look at the issues I created for some best practice adjustments as well as some more advanced techniques you can start looking into. Your results look professional, now it's time to work on making your code look as professional. Incorporating more semantic tags and maybe adopting a professional CSS naming convention will help with this. Check out the BEM method, but there are others as well: http://getbem.com/introduction/

Well done, I hope you enjoyed the course!

**Comment by vitaliigrybov** [comment]
Thank you Ryan for your review. I appreciate your advices!
